from typing import List, Optional

import vkdispatch.base.dtype as dtypes

from .base import CodeGenBackend


class OpenCLBackend(CodeGenBackend):
    name = "opencl"

    _SCALAR_TYPE_NAMES = {
        dtypes.int16: "short",
        dtypes.uint16: "ushort",
        dtypes.int32: "int",
        dtypes.uint32: "uint",
        dtypes.int64: "long",
        dtypes.uint64: "ulong",
        dtypes.float16: "half",
        dtypes.float32: "float",
        dtypes.float64: "double",
    }

    def __init__(self) -> None:
        self.reset_state()

    def reset_state(self) -> None:
        self._kernel_params: List[str] = []
        self._entry_alias_lines: List[str] = []

    def _register_kernel_param(self, param_decl: str) -> None:
        if param_decl not in self._kernel_params:
            self._kernel_params.append(param_decl)

    def _register_alias_line(self, alias_line: str) -> None:
        self._entry_alias_lines.append(alias_line)

    @classmethod
    def _scalar_type_name(cls, scalar_type: dtypes.dtype) -> str:
        type_name = cls._SCALAR_TYPE_NAMES.get(scalar_type)
        if type_name is None:
            raise ValueError(f"Unsupported OpenCL scalar type mapping for '{scalar_type.name}'")
        return type_name

    def type_name(self, var_type: dtypes.dtype) -> str:
        if dtypes.is_scalar(var_type):
            return self._scalar_type_name(var_type)

        if dtypes.is_vector(var_type):
            return f"{self._scalar_type_name(var_type.scalar)}{var_type.child_count}"

        if dtypes.is_complex(var_type):
            return f"{self._scalar_type_name(var_type.child_type)}2"

        if dtypes.is_matrix(var_type):
            raise NotImplementedError("matrix types (mat2/mat3/mat4) unsupported in OpenCL MVP")

        raise ValueError(f"Unsupported OpenCL type mapping for '{var_type.name}'")

    def constructor(self, var_type: dtypes.dtype, args: List[str]) -> str:
        target_type = self.type_name(var_type)

        if dtypes.is_scalar(var_type):
            assert len(args) > 0, f"Constructor for scalar type '{var_type.name}' needs at least one argument."
            return f"(({target_type})({args[0]}))"

        return f"{target_type}({', '.join(args)})"

    def component_access_expr(self, expr: str, component: str, base_type: dtypes.dtype) -> str:
        if dtypes.is_scalar(base_type) and component == "x":
            return expr
        return super().component_access_expr(expr, component, base_type)

    def binary_math_expr(
        self,
        func_name: str,
        lhs_type: dtypes.dtype,
        lhs_expr: str,
        rhs_type: dtypes.dtype,
        rhs_expr: str,
    ) -> str:
        mapped = self.math_func_name(func_name, lhs_type)
        return f"{mapped}({lhs_expr}, {rhs_expr})"

    def pre_header(self, *, enable_subgroup_ops: bool, enable_printf: bool) -> str:
        _ = enable_subgroup_ops
        _ = enable_printf
        return (
            "// OpenCL C source generated by vkdispatch\n"
            "#ifdef cl_khr_fp64\n"
            "#pragma OPENCL EXTENSION cl_khr_fp64 : enable\n"
            "#endif\n"
            "#ifdef cl_khr_fp16\n"
            "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
            "#endif\n"
        )

    def make_source(self, header: str, body: str, x: int, y: int, z: int) -> str:
        workgroup_attribute = f"__attribute__((reqd_work_group_size({x}, {y}, {z})))"
        if "__kernel void vkdispatch_main" in body:
            body = body.replace(
                "__kernel void vkdispatch_main",
                f"{workgroup_attribute}\n__kernel void vkdispatch_main",
                1,
            )
        else:
            body = f"{workgroup_attribute}\n{body}"

        return f"{header}\n{body}"

    def constant_namespace(self) -> str:
        return "UBO"

    def variable_namespace(self) -> str:
        return "UBO"

    def exec_bounds_guard(self, exec_count_expr: str) -> str:
        gid_expr = f"({self.global_invocation_id_expr()})"
        exec_expr = f"({exec_count_expr})"
        return (
            f"if ({self.component_access_expr(exec_expr, 'x', dtypes.uvec4)} <= {self.component_access_expr(gid_expr, 'x', dtypes.uvec3)} || "
            f"{self.component_access_expr(exec_expr, 'y', dtypes.uvec4)} <= {self.component_access_expr(gid_expr, 'y', dtypes.uvec3)} || "
            f"{self.component_access_expr(exec_expr, 'z', dtypes.uvec4)} <= {self.component_access_expr(gid_expr, 'z', dtypes.uvec3)}) {{ return; }}\n"
        )

    def shared_buffer_declaration(self, var_type: dtypes.dtype, name: str, size: int) -> str:
        return f"__local {self.type_name(var_type)} {name}[{size}];"

    def uniform_block_declaration(self, contents: str) -> str:
        self._register_kernel_param("__global const UniformObjectBuffer* vkdispatch_uniform_ptr")
        self._register_alias_line("const UniformObjectBuffer UBO = *vkdispatch_uniform_ptr;")
        return f"\ntypedef struct UniformObjectBuffer {{\n{contents}\n}} UniformObjectBuffer;\n"

    def storage_buffer_declaration(self, binding: int, var_type: dtypes.dtype, name: str) -> str:
        struct_name = f"Buffer{binding}"
        param_name = f"vkdispatch_binding_{binding}_ptr"
        data_type = self.type_name(var_type)
        self._register_kernel_param(f"__global {data_type}* {param_name}")
        self._register_alias_line(f"{struct_name} {name} = {{{param_name}}};")
        return f"typedef struct {struct_name} {{ __global {data_type}* data; }} {struct_name};\n"

    def sampler_declaration(self, binding: int, dimensions: int, name: str) -> str:
        _ = (binding, dimensions, name)
        raise NotImplementedError("image/sampler unsupported in OpenCL MVP")

    def push_constant_declaration(self, contents: str) -> str:
        _ = contents
        raise NotImplementedError("push constants unsupported for OpenCL backend")

    def entry_point(self, body_contents: str) -> str:
        params = ", ".join(self._kernel_params)
        alias_block = ""
        for line in self._entry_alias_lines:
            alias_block += f"    {line}\n"

        return (
            f"__kernel void vkdispatch_main({params}) {{\n"
            f"{alias_block}"
            f"{body_contents}"
            f"}}\n"
        )

    def inf_f32_expr(self) -> str:
        return "as_float((uint)0x7F800000u)"

    def ninf_f32_expr(self) -> str:
        return "as_float((uint)0xFF800000u)"

    def float_bits_to_int_expr(self, var_expr: str) -> str:
        return f"as_int({var_expr})"

    def float_bits_to_uint_expr(self, var_expr: str) -> str:
        return f"as_uint({var_expr})"

    def int_bits_to_float_expr(self, var_expr: str) -> str:
        return f"as_float({var_expr})"

    def uint_bits_to_float_expr(self, var_expr: str) -> str:
        return f"as_float({var_expr})"

    def global_invocation_id_expr(self) -> str:
        return "((uint3)((uint)get_global_id(0), (uint)get_global_id(1), (uint)get_global_id(2)))"

    def local_invocation_id_expr(self) -> str:
        return "((uint3)((uint)get_local_id(0), (uint)get_local_id(1), (uint)get_local_id(2)))"

    def local_invocation_index_expr(self) -> str:
        return (
            "((uint)(get_local_id(0) + "
            "get_local_size(0) * (get_local_id(1) + get_local_size(1) * get_local_id(2))))"
        )

    def workgroup_id_expr(self) -> str:
        return "((uint3)((uint)get_group_id(0), (uint)get_group_id(1), (uint)get_group_id(2)))"

    def workgroup_size_expr(self) -> str:
        return "((uint3)((uint)get_local_size(0), (uint)get_local_size(1), (uint)get_local_size(2)))"

    def num_workgroups_expr(self) -> str:
        return "((uint3)((uint)get_num_groups(0), (uint)get_num_groups(1), (uint)get_num_groups(2)))"

    def num_subgroups_expr(self) -> str:
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_id_expr(self) -> str:
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_size_expr(self) -> str:
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_invocation_id_expr(self) -> str:
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def barrier_statement(self) -> str:
        return "barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE);"

    def memory_barrier_statement(self) -> str:
        return "mem_fence(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE);"

    def memory_barrier_buffer_statement(self) -> str:
        return "mem_fence(CLK_GLOBAL_MEM_FENCE);"

    def memory_barrier_shared_statement(self) -> str:
        return "mem_fence(CLK_LOCAL_MEM_FENCE);"

    def memory_barrier_image_statement(self) -> str:
        raise NotImplementedError("image/sampler unsupported in OpenCL MVP")

    def group_memory_barrier_statement(self) -> str:
        return "mem_fence(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE);"

    def subgroup_add_expr(self, arg_expr: str) -> str:
        _ = arg_expr
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_mul_expr(self, arg_expr: str) -> str:
        _ = arg_expr
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_min_expr(self, arg_expr: str) -> str:
        _ = arg_expr
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_max_expr(self, arg_expr: str) -> str:
        _ = arg_expr
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_and_expr(self, arg_expr: str) -> str:
        _ = arg_expr
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_or_expr(self, arg_expr: str) -> str:
        _ = arg_expr
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_xor_expr(self, arg_expr: str) -> str:
        _ = arg_expr
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_elect_expr(self) -> str:
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def subgroup_barrier_statement(self) -> str:
        raise NotImplementedError("subgroup operations unsupported in OpenCL MVP")

    def printf_statement(self, fmt: str, args: List[str]) -> str:
        if len(args) == 0:
            return f'printf("{fmt}");'
        return f'printf("{fmt}", {", ".join(args)});'

    def texture_size_expr(self, texture_expr: str, lod: int, dimensions: int) -> str:
        _ = (texture_expr, lod, dimensions)
        raise NotImplementedError("image/sampler unsupported in OpenCL MVP")

    def sample_texture_expr(self, texture_expr: str, coord_expr: str, lod_expr: Optional[str] = None) -> str:
        _ = (texture_expr, coord_expr, lod_expr)
        raise NotImplementedError("image/sampler unsupported in OpenCL MVP")

    def mark_texture_sample_dimension(self, dimensions: int) -> None:
        _ = dimensions
        raise NotImplementedError("image/sampler unsupported in OpenCL MVP")
