import vkdispatch_native

from .context import Handle
from .errors import check_for_compute_stage_errors, check_for_errors


class ComputePlan(Handle):
    """
    Represents a compiled Compute Pipeline ready for execution.

    A ComputePlan wraps the native Vulkan pipeline objects, including the shader module, 
    descriptor set layouts, and pipeline layouts. It is created by compiling GLSL 
    source code generated by the ``vkdispatch.codegen`` module.

    :param shader_source: The GLSL source code for the compute shader.
    :type shader_source: str
    :param binding_type_list: A list of integers representing the type of resource 
                              bound to each binding index.
    :type binding_type_list: list
    :param pc_size: The size of the push constant block in bytes.
    :type pc_size: int
    :param shader_name: A name for the shader, used for debugging and logging.
    :type shader_name: str
    """

    def __init__(self, shader_source: str, binding_type_list: list, pc_size: int, shader_name: str) -> None:
        super().__init__()

        self.pc_size = pc_size
        self.shader_source = shader_source
        self.binding_list = binding_type_list

        handle = vkdispatch_native.stage_compute_plan_create(
            self.context._handle, shader_source.encode(), self.binding_list, pc_size, shader_name.encode()
        )
        check_for_compute_stage_errors()
        
        self.register_handle(handle)

    def _destroy(self) -> None:
        vkdispatch_native.stage_compute_plan_destroy(self._handle)
        check_for_errors()
    
    def __del__(self) -> None:
        self.destroy()
